version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: upgrade pyenv
          command: |
            cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -
      - restore_cache:
          keys:
            - v1-pythons-{{ checksum "pyenv_install_pythons.sh" }}
            - v1-pythons-
      - run:
          name: install pythons for testing
          command: |
            ./pyenv_install_pythons.sh
      - save_cache:
          paths:
            - /opt/circleci/.pyenv/versions/
          key: v1-pythons-{{ checksum "pyenv_install_pythons.sh" }}
      - run:
          name: Build Docker images
          command: |
            docker-compose -f ./tests/pytest_docker_compose_tests/my_network/docker-compose.yml build
      - run:
          name: install package and run tests
          command: |
            pyenv global 3.6.9
            pip install tox tox-pyenv
            pyenv local 3.5.2 3.6.9
            tox
  publish:
    docker:
      - image: circleci/python:3.8.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: create packages
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: upload to pypi
          command: |
            set -o nounset
            pip install --user twine
            PATH=/home/circleci/.local/bin:$PATH
            twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
